//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosOnline.EFDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PwaEntities : DbContext
    {
        public PwaEntities()
            : base("name=PwaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentroMedico> CentroMedico { get; set; }
        public virtual DbSet<Dias> Dias { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<HorariosProfesional> HorariosProfesional { get; set; }
        public virtual DbSet<ObrasSociales> ObrasSociales { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<ProfesionalCentroMedico> ProfesionalCentroMedico { get; set; }
        public virtual DbSet<Profesionales> Profesionales { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
    
        public virtual int pa_DeleteHorariosDoctor(Nullable<int> idProfesional)
        {
            var idProfesionalParameter = idProfesional.HasValue ?
                new ObjectParameter("IdProfesional", idProfesional) :
                new ObjectParameter("IdProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_DeleteHorariosDoctor", idProfesionalParameter);
        }
    
        public virtual int pa_DeleteProfesionalCentroMedico(Nullable<int> idProfesional)
        {
            var idProfesionalParameter = idProfesional.HasValue ?
                new ObjectParameter("IdProfesional", idProfesional) :
                new ObjectParameter("IdProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_DeleteProfesionalCentroMedico", idProfesionalParameter);
        }
    }
}
