//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosOnline.EFDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorariosProfesional
    {
        public int IdProfesional { get; set; }
        public int IdCentroMedico { get; set; }
        public int IdDia { get; set; }
        public string HoraDesde { get; set; }
        public string HoraHasta { get; set; }
        public int IdHorario { get; set; }
    
        public virtual CentroMedico CentroMedico { get; set; }
        public virtual Dias Dias { get; set; }
        public virtual Profesionales Profesionales { get; set; }
    }
}
