//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosOnline.EFDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesionalCentroMedico
    {
        public int IdProfesional { get; set; }
        public int IdCentroMedico { get; set; }
        public string DiasAtencion { get; set; }
        public Nullable<int> MaxHoraDesde { get; set; }
        public Nullable<int> MaxHoraHasta { get; set; }
        public string DuracionTurno { get; set; }
    
        public virtual CentroMedico CentroMedico { get; set; }
        public virtual Profesionales Profesionales { get; set; }
    }
}
