//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosOnline.EFDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesionales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesionales()
        {
            this.HorariosProfesional = new HashSet<HorariosProfesional>();
            this.ProfesionalCentroMedico = new HashSet<ProfesionalCentroMedico>();
            this.Turnos = new HashSet<Turnos>();
        }
    
        public int IdProfesional { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cuit { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public byte[] Imagen { get; set; }
        public string TelefonoParticular { get; set; }
        public string Email { get; set; }
        public string ImageData { get; set; }
        public string TelefonoCelular { get; set; }
        public string Observaciones { get; set; }
        public string MNacional { get; set; }
        public string MProvincial { get; set; }
        public string CBU { get; set; }
    
        public virtual Especialidades Especialidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosProfesional> HorariosProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesionalCentroMedico> ProfesionalCentroMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turnos> Turnos { get; set; }
    }
}
